---
version: 1.3
slug: gotify
name: Gotify
init: false
description: >-
  A self-hosted push notification service
url: https://github.com/chriss158/addons/tree/master/gotify
init: false
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
  - i386
webui: http://[HOST]:[PORT:8069]
ingress: true
ingress_port: 80
panel_admin: true
panel_icon: mdi:message-text-outline
map:
 - addon_config:rw
 - ssl
ports:
  80/tcp: 8069
  443/tcp: 8074
ports_description:
  80/tcp: Web interface (Not required for Ingress)
  443/tcp: Web interface (With SSL)
options:
  database: sqlite3
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  database: list(sqlite3|mysql|postgres)?
  database_connection: str?
  registration: bool?
  ssl: bool
  certfile: str
  keyfile: str
startup: system
